// API endpoints
export const API_ENDPOINTS = {
    auth: {
        login: '/login',
        register: '/register',
        logout: '/logout',
        profile: '/user/profile',
    },
    projects: {
        board: (projectId) => `/projects/${projectId}/board`,
        list: '/user/projects',
        detail: (projectId) => `/projects/${projectId}`,
        create: '/projects',
        createDefault: '/projects/default',
        update: (projectId) => `/projects/${projectId}`,
        delete: (projectId) => `/projects/${projectId}`,
        members: (projectId) => `/projects/${projectId}/members`,
        statuses: (projectId) => `/projects/${projectId}/statuses`,
        lanes: (projectId) => `/projects/${projectId}/lanes`,
        tasks: (projectId) => `/projects/${projectId}/tasks`,
        profile: (projectId) => `/projects/${projectId}/profile`,
        projectActivity: (projectId, limit, offset) => `/projects/${projectId}/activities?limit=${limit}&offset=${offset}`,
        summary: (projectId, period = '30d') => `/projects/${projectId}/summary?period=${period}`,
    },
    members: {
        profile: (projectId, userId) => `/projects/${projectId}/members/${userId}`,
        create: (projectId) => `/projects/${projectId}/members`,
        update: (projectId, userId) => `/projects/${projectId}/members/${userId}`,
        delete: (projectId, userId) => `/projects/${projectId}/members/${userId}`,
        activities: (projectId, userId, limit, offset) => `/projects/${projectId}/members/${userId}/activities?limit=${limit}&offset=${offset}`,
    },
    lanes: {
        create: (projectId) => `/projects/${projectId}/lanes`,
        update: (projectId, laneId) => `/projects/${projectId}/lanes/${laneId}`,
        delete: (projectId, laneId) => `/projects/${projectId}/lanes/${laneId}`,
        reorder: (projectId) => `/projects/${projectId}/lanes/reorder`,
    },
    columns: {
        create: (projectId) => `/projects/${projectId}/columns`,
        delete: (projectId, columnId) => `/projects/${projectId}/columns/${columnId}`,
        reorder: (projectId) => `/projects/${projectId}/columns/reorder`,
    },
    tasks: {
        create: (projectId) => `/projects/${projectId}/tasks`,
        update: (projectId, taskId) => `/projects/${projectId}/tasks/${taskId}`,
        detail: (projectId, taskId) => `/projects/${projectId}/tasks/${taskId}`,
        list: (projectId, query) => `/projects/${projectId}/tasks?${query}`,
        activities: (projectId, taskId, limit = 30, offset = 0) => `/projects/${projectId}/tasks/${taskId}/activities?limit=${limit}&offset=${offset}`,
        comments: (projectId, taskId, limit = 30, offset = 0) => `/projects/${projectId}/tasks/${taskId}/comments?limit=${limit}&offset=${offset}`,
        changes: (projectId, taskId, fieldName = "", limit = 30, offset = 0) => `/projects/${projectId}/tasks/${taskId}/changes?limit=${limit}&offset=${offset}&fieldName=${fieldName}`,
        updateStatus: (projectId, taskId) => `/projects/${projectId}/tasks/${taskId}`,
        addTag: (projectId, taskId, tagId) => `/projects/${projectId}/tasks/${taskId}/tags?tag_id=${tagId}`,
        removeTag: (projectId, taskId, tagId) => `/projects/${projectId}/tasks/${taskId}/tags?tag_id=${tagId}`,
    },
    comments: {
        create: (projectId, taskId) => `/projects/${projectId}/tasks/${taskId}/comments`,
        update: (commentId) => `/comments/${commentId}`,
        delete: (commentId) => `/comments/${commentId}`,
    },
    attachments: {
        upload: (projectId, taskId) => `/projects/${projectId}/tasks/${taskId}/attachments`,
        download: (projectId, taskId, attachmentId) => `/projects/${projectId}/tasks/${taskId}/attachments/${attachmentId}`,
        delete: (projectId, taskId, attachmentId) => `/projects/${projectId}/tasks/${taskId}/attachments/${attachmentId}`,
    },
    statuses: {
        create: (projectId) => `/projects/${projectId}/statuses`,
        update: (projectId, statusId) => `/projects/${projectId}/statuses/${statusId}`,
        delete: (projectId, statusId) => `/projects/${projectId}/statuses/${statusId}`,
    },
    tags: {
        list: (projectId) => `/projects/${projectId}/tags`,
        create: (projectId) => `/projects/${projectId}/tags`,
        update: (tagId) => `/tags/${tagId}`,
        delete: (projectId, tagId) => `/projects/${projectId}/tags/${tagId}`,
    },
    search: {
        tasks: '/search/tasks',
        projects: '/search/projects',
        users: (query) => `/users/search?search=${query}`,
    },
};